apiVersion: v1
kind: Pod
metadata:
  name: sysctl-tuner
  namespace: default
spec:
  hostPID: true
  hostNetwork: true
  hostIPC: true
  containers:
  - name: sysctl-tuner
    image: busybox
    command: ["sh", "-c", "sleep infinity"]
    securityContext:
      privileged: true
      capabilities:
        add:
        - SYS_ADMIN
        - SYS_PTRACE
        - NET_ADMIN
    volumeMounts:
    - name: proc
      mountPath: /host-proc
    - name: sys
      mountPath: /host-sys
  volumes:
  - name: proc
    hostPath:
      path: /proc
      type: Directory
  - name: sys
    hostPath:
      path: /sys
      type: Directory
  restartPolicy: Never
  tolerations:
  - operator: Exists
    effect: NoSchedule
  - operator: Exists
    effect: NoExecute

