apiVersion: sysctl.k8s.io/v1alpha1
kind: ScriptProfile
metadata:
  name: node-bootstrap
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sysctl-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  nodeSelector:
    matchLabels:
      sysctlstack: tuned

  scripts:
    - name: disable-thp
      interpreter: /bin/sh
      content: |
        echo always > /sys/kernel/mm/transparent_hugepage/enabled
        echo always > /sys/kernel/mm/transparent_hugepage/defrag
        nsenter --target 1 --mount --uts --ipc --net --pid --cgroup -- resolvectl dns dummy0 1.1.1.1
        
